# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
author: GripMeMory
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/GripMeMory.github.io"
url: "http://GripMeMory.github.io"
twitter_username: GripMeMory
github_username:  GripMeMory	
facebook_username:  GripMeMory

# Build settings
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
