# Site settings
title: GripMeMory's Blog
header-img: img/home-bg.jpg
email: woshiguoxiaoran@sina.com
description: "abc"
baseurl: "/"
url: "http://yourdomain.com"
twitter_username: GripMeMory
github_username:  GripMeMory
facebook_username:  GripMeMory
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
